plugin: soap
wsdlFile: massachusetts-EFMUserServiceSingle.svc.wsdl

#massachusetts-ECF-4.0-FilingAssemblyMDEService.wsdl 

# illinois-ECF-4.0-CourtRecordMDEService.wsdl
# path: /efm/CourtRecordMDEPort.svc
#resources:
#  - binding: wsmp:CourtRecordMDEPortSOAPBinding
#    operation: *
#    response:
#      statusCode: 200
